### PR TITLE
CPLP-1587: Modal dialog adjustments

### PR DESCRIPTION
**Pull request by bcasparraysono**
* Refactor modal dialog default width
* Add better integration for MUI maxWidth and fullWidth settings
* Expand Storybook story
* Center text content by default

### CODE REVIEW

**Comment by jjeroch** [comment]
@oyo you have the merge master right ;)

@manojava-gk  @nidhigarg-bmw  @lavanya-bmw  modal gets updated with this pr - adjustment such as sizing, content location and width is changed.

**Review by nidhigarg-bmw — DISMISSED** [review]
lgtm

**Comment by bcasparraysono** [comment]
@oyo OK, now the code smells are growing instead of shrinking!
I fixed the one code smell in my code. The other old and new code smells are from someone else's code and appeared because I rebased my PR onto `dev` before pushing.
Should I fix them anyway?

**Comment by oyo** [comment]
@bcasparraysono having a look into the rule description there is simple compliant solution - just write the handlers as conventional functions:

instead of
`const handleEvent = (...) => {...}`

write as
`function handleEvent(...) {...}`

and then always just give the handler not wrapping it in an anonymous arrow function
`<Component onClick={handleEvent}></Component>`

**Comment by bcasparraysono** [comment]
Not working unfortunately.. now we getting the next one: `JSX props should not use functions`

**Pull request merged**
