### PR TITLE
bugfix/typography setup

### PR DESCRIPTION
**Pull request by jjeroch**
Typo corrected for headlines

### CODE REVIEW

**Comment by jjeroch** [comment]
The PR is correcting the incorrect setting of the Typography of our project. However the impact will be huge. So lets discuss jointly when we merge the pr.

**Comment by jjeroch** [comment]
Just discussed the case in the FE Developer call and aligned that we merge the pr.
In the upcoming 3-5 working days Julia will (as part of normal tests) run through the FE screens and correct where needed the used header variant

**Review by manojava-gk — APPROVED** [review]
lgtm

**Review by oyo — APPROVED** [review]
okay

**Pull request merged**
