### PR TITLE
CPLP-1016: Fix shared custom typography definitions bundling

### PR DESCRIPTION
**Pull request by bcasparraysono**
* Fix library bundling for custom MUI typography Typescript definitions in `cx-portal-shared-components`
* Reduce `cx-portal-shared-components` bundle size by optimizing lodash imports

### CODE REVIEW

**Comment by jjeroch** [comment]
Ah great, thats the area which I expected to be the issue.
Looks good but I guess we need the code smell fixes again. @oyo am I right?

**Comment by bcasparraysono** [comment]
@jjeroch I already talked to @oyo about the code smells... They are all in code places that my PR didn't touch. They are appearing now because on Dec. 7 a new rule got added to Sonarcloud, and now it is complaining about that rule in the preexisting code base.

**Comment by BernieCr** [comment]
@oyo I tried that out, but it didn't work unfortunately because then we were getting hit by the next rule that said not to use normal functions either.
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&pullRequest=15&id=catenax-ng_tx-portal-frontend&open=AYUFEDevRQMHHzxpbIyC

**Comment by bcasparraysono** [comment]
@oyo I tried that out, but it didn't work unfortunately, because then we were getting hit by the next rule, which said not to use normal functions either.
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&pullRequest=15&id=catenax-ng_tx-portal-frontend&open=AYUFEDevRQMHHzxpbIyC

**Comment by oyo** [comment]
@bcasparraysono quite ironic they suggest this solution in the rule description and then that triggers another smell...
image

**Comment by manojava-gk** [comment]
useCallback helped me to fix the code smell

```const handleClick = useCallback(() => {}, [])```

**Comment by bcasparraysono** [comment]
Please wait with merging, I noticed that I need to look into the portal code because now we got some Typescript errors.

**Comment by bcasparraysono** [comment]
OK, now the portal is compiling again

**Review by jjeroch — APPROVED** [review]

**Pull request merged**
