### PR TITLE
change_update company intro page

### PR DESCRIPTION
**Pull request by jjeroch**

### CODE REVIEW

**Comment by manojava-gk** [comment]
> @manojava-gk any idea how we get from this: image
> 
> to this: image
> 
> => instead of 2 description rows we would have 4; and the space between title and description is reduced
> 
> For the other text boxes, small change from image
> 
> to this image

In this file CardWithText.tsx,

update WebkitLineClamp attribute in the sx props to 2 and 4 respectively.

**Comment by manojava-gk** [comment]
> @manojava-gk any idea how we get from this: image
> 
> to this: image
> 
> => instead of 2 description rows we would have 4; and the space between title and description is reduced
> 
> For the other text boxes, small change from image
> 
> to this image

image

image

image

Is this fine now? @jjeroch

**Comment by jjeroch** [comment]
@manojava-gk looks much better - the only small adjustment: 
image

ideally the description is starting on the same height (means keep an empty row in the first box) - in case this is easy possible I'll appreciate if you can do it. If this is a bit more time consuming, we do it later and I merge this pr.

**Comment by manojava-gk** [comment]
> @manojava-gk looks much better - the only small adjustment: image
> 
> ideally the description is starting on the same height (means keep an empty row in the first box) - in case this is easy possible I'll appreciate if you can do it. If this is a bit more time consuming, we do it later and I merge this pr.

I do not have a solution for this right now. You can merge this PR. I will check and create another PR with the fix

**Comment by jjeroch** [comment]
> > @manojava-gk looks much better - the only small adjustment: image
> > ideally the description is starting on the same height (means keep an empty row in the first box) - in case this is easy possible I'll appreciate if you can do it. If this is a bit more time consuming, we do it later and I merge this pr.
> 
> I do not have a solution for this right now. You can merge this PR. I will check and create another PR with the fix

@manojava-gk can only merge if you approve the pr - please approve

**Review by manojava-gk — APPROVED** [review]
looks good

**Pull request merged**
